// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abocpiuhhlhnzyylsigs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFib2NwaXVoaGxobnp5eWxzaWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTIyMzEsImV4cCI6MjA2NDEyODIzMX0.6lNX0VDmkyNptM0C-8Ipr39tVc4x27wt4c6fV-kzJSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);